### PR TITLE
SettingsPage is created
SettingsDefs is created
Settings feature is created

### PR DESCRIPTION
**Pull request by glpylmz26**

### CODE REVIEW

**Review by hiltas73 — APPROVED** [review]
seems fine

**Review by hiltas73 — APPROVED** [review]

**Review by hiltas73 — APPROVED** [review]
seems no conflict

**Review by Denadoshkoza — APPROVED** [review]

**Review by Denadoshkoza — APPROVED** [review]

**Comment by Denadoshkoza** [comment]
is all good(i guess

**Review by Denadoshkoza — APPROVED** [review]

**Review by Denadoshkoza — APPROVED** [review]

**Review by Denadoshkoza — APPROVED** [review]

**Comment by Denadoshkoza** [comment]
rubish

**Review by Denadoshkoza — APPROVED** [review]

**Review by Denadoshkoza — APPROVED** [review]
bla bla

**Review by hiltas73 — APPROVED** [review]
bla

**Review by Denadoshkoza — APPROVED** [review]

**Review by hiltas73 — APPROVED** [review]
bla

**Review by Mamlakat — APPROVED** [review]

**Pull request closed without merging**
